### PR TITLE
Components docs

### PR DESCRIPTION
**Pull request by rbarbey**

### CODE REVIEW

**Comment by PoslinskiNet** [comment]
@praskovia-root maybe we could gradually merge it now, with some leftover of todos as JIRA tasks or Github issue (if any)?

**Comment by praskovia-root** [comment]
@PoslinskiNet At the present moment articles about 2 components are ready: ax-icon and ax-checkbox.
@rbarbey Is it OK to merge it like this? Or is it better to create placeholder articles for the remaining components first?

**Comment by PoslinskiNet** [comment]
@praskovia-root just small linter issues cause 🔴 build:

image

**Review by praskovia-root — APPROVED** [review]
The docs are available under / which redirects to /docs. 
image

**Pull request merged**
