### PR TITLE
Add mouseEnter and mouseLeave to the ax-table/row

### PR DESCRIPTION
**Pull request by mikoscz**
# Tasks:
- [ ] Add onMouseEnter hook for the table row.
- [ ] Add onMouseLeave hook for the table row.

# Added value:
- [ ] Allow us to trigger actions when the user hovers table row

### CODE REVIEW

**Review by praskovia-root — COMMENTED** [review]
hbs linter throws ['no-invalid-interactive' error](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-invalid-interactive.md)
That means, that if an interaction can be performed with an element which is not interactive by default (like button etc.), this element should get a corresponding aria-role. I'm not sure whether the role 'button' would semantically fit there or not. If not, we can also disable this rule for TR. @mikoscz , @rbarbey what do you think?

**Comment by mikoscz** [comment]
This one is a little bit tricky - it is a base component I think that adding the aria role button isn't a good idea here. I was thinking about disabling this one here. But maybe there is a corresponding role that addresses the use case. What do you think?

**Comment by praskovia-root** [comment]
> 
> 
> This one is a little bit tricky - it is a base component I think that adding the aria role button isn't a good idea here. I was thinking about disabling this one here. But maybe there is a corresponding role that addresses the use case. What do you think?

I tried to find a role which could fit, but since use cases for handling of these events may be different in different tables, I haven't found anything generic enough. I propose to disable this rule for roles using 'ignoredTags' array in lintconfig.

**Comment by mikoscz** [comment]
@praskovia-root should we enfore adding corresponding aria role whenever one of those hooks are used? I mean when one or both are passed to the component then `aria-role` should be required.

**Comment by praskovia-root** [comment]
@mikoscz yes, at least we should point it out in the documentation.

**Review by PoslinskiNet — APPROVED** [review]

**Pull request merged**
